name: Hello World

on: 
  workflow_dispatch:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: static index.html

      - name: Cache node_modules
        id: cache_node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/index.html') }}

      - name: static files 
        id: static_files
        run: echo "::set-output name=filenames::$(ls  | tr '\n' ' ')"

      - name: show files 
        run: echo "${{ steps.static_files.outputs.filenames }}"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: npm i -S create-react-app concurrently express dotenv react react-dom jest puppeteer discord.js

      - run: ls

      # - name: Commit and push files 
      #   run: |
      #     git config --global user.email "octocat@github.com"
      #     git config --global user.name "Github Actions"
      #     git init
      #     git remote add origin https://fizal619:${{ secrets.GITHUB_TOKEN }}@github.com/fizal619/cat-app.git
      #     git checkout -b pages
      #     git add . 
      #     git commit -m "Deploying 🚀"
      #     git push origin pages -f


