name: Hello World

on: 
  workflow_dispatch:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: static index.html

      - name: Commit and push files 
        run: |
          git init
          git checkout -b pages
          git add . 
          git commit -m "Deploying 🚀"
          git push origin pages -f


